// Code generated by "stringer -type=UserAction"; DO NOT EDIT

package main

import "fmt"

const _UserAction_name = "ScrapingDownloading"

var _UserAction_index = [...]uint8{0, 8, 19}

func (i UserAction) String() string {
	i -= 1
	if i < 0 || i >= UserAction(len(_UserAction_index)-1) {
		return fmt.Sprintf("UserAction(%d)", i+1)
	}
	return _UserAction_name[_UserAction_index[i]:_UserAction_index[i+1]]
}
